
/*
 * generated by Xtext
 */
 
package org.ow2.fractal.mind.idl;

import org.eclipse.xtext.ui.core.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class FractalItfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.ow2.fractal.mind.idl.internal.FractalItfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.ow2.fractal.mind.idl.internal.FractalItfActivator.getInstance().getInjector("org.ow2.fractal.mind.idl.FractalItf");
	}
	
}
