/*
* generated by Xtext
*/
package org.ow2.fractal.mind.idl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.ow2.fractal.mind.idl.fractalIDL.ConstantDefinition;
import org.ow2.fractal.mind.idl.fractalIdt.ConstantDefinitionBegin;
import org.ow2.fractal.mind.idl.fractalIdt.ConstantDefinitionEnd;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 * 
 * @author Damien Fournier
 */

public class FractalIdtLabelProvider extends FractalItfLabelProvider {

	@Inject
	public FractalIdtLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	public String image(ConstantDefinitionBegin obj) {
		return "define_obj.gif";
	}
	
	public String image(ConstantDefinitionEnd obj) {
		return "define_obj.gif";
	}
	
	public String image(ConstantDefinition obj) {
		return "define_obj.gif";

	}
	
}
