/*
 * generated by Xtext
 */
package org.ow2.fractal.mind.idl;

import org.eclipse.xtext.ui.common.editor.syntaxcoloring.ILexicalHighlightingConfiguration;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author Rémi Mélisson
 */
public class FractalItfUiModule extends org.ow2.fractal.mind.idl.AbstractFractalItfUiModule {
	/**
	 * register syntax coloring
	 * @return class which define MIND ITF syntax coloring
	 */
	public Class<? extends ILexicalHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return LexicalHighlightingConfiguration.class;
		}
	
	/**
	 * register mapping tokens to IDs
	 * @return MIND ITF tokens mapping
	 */
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeIdMapper.class;
		}
	
}
