/*
 * generated by Xtext
 */
package org.ow2.fractal.mind.idl;

import org.eclipse.xtext.ui.common.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author Rémi Mélisson
 */
public class FractalItfUiModule extends
		org.ow2.fractal.mind.idl.AbstractFractalItfUiModule {
	/**
	 * register syntax coloring
	 * 
	 * @return class which define MIND ITF syntax coloring
	 */
	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return LexicalHighlightingConfiguration.class;
	}

	/**
	 * register mapping tokens to IDs
	 * 
	 * @return MIND ITF tokens mapping
	 */
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeIdMapper.class;
	}

	/**
	 * register semantic coloring
	 * 
	 * @return class which define the token that will be highlighted
	 */
//	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
//		return SemanticHighlightingCalculator.class;
//	}

}
