/*
* generated by Xtext
*/
package org.ow2.fractal.mind.idl.contentassist;

import org.ow2.fractal.mind.idl.contentassist.AbstractFractalItfProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FractalItfProposalProvider extends AbstractFractalItfProposalProvider {

}
