/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.ow2.fractal.mind.ide.emf.mindide.validation;

import org.ow2.fractal.mind.ide.emf.mindide.MindObject;
import org.ow2.fractal.mind.ide.emf.mindide.MindPathKind;
import org.ow2.fractal.mind.ide.emf.mindide.MindProject;

/**
 * A sample validator interface for {@link org.ow2.fractal.mind.ide.emf.mindide.MindPathEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MindPathEntryValidator {
	boolean validate();

	boolean validateOwnerProject(MindProject value);
	boolean validateResolvedBy(MindObject value);
	boolean validateEntryKind(MindPathKind value);
}
