/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.ow2.fractal.mind.ide.emf.mindide.validation;

import java.net.URI;

import org.eclipse.emf.common.util.EList;

import org.ow2.fractal.mind.ide.emf.mindide.MindPackage;
import org.ow2.fractal.mind.ide.emf.mindide.MindProject;
import org.ow2.fractal.mind.ide.emf.mindide.MindRepo;
import org.ow2.fractal.mind.ide.emf.mindide.MindRootSrc;

/**
 * A sample validator interface for {@link org.ow2.fractal.mind.ide.emf.mindide.MindRootSrc}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MindRootSrcValidator {
	boolean validate();

	boolean validatePackages(EList<MindPackage> value);
	boolean validateProject(MindProject value);
	boolean validateRepo(MindRepo value);
	boolean validateFullpath(String value);
	boolean validateFolder(URI value);
	boolean validateDependencies(EList<MindRootSrc> value);
}
