/*
* generated by Xtext
*/
package org.ow2.mindEd.idt.editor.textual.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import org.ow2.mindEd.idt.editor.textual.services.FractalIdtGrammarAccess;

public class FractalIdtParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FractalIdtGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		TokenSource tokenSource = createLexer(in);
		XtextTokenStream tokenStream = createTokenStream(tokenSource);
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.ow2.mindEd.idt.editor.textual.parser.antlr.internal.InternalFractalIdtParser parser = createParser(tokenStream);
		parser.setTokenTypeMap(getTokenDefProvider().getTokenDefMap());
		parser.setSyntaxErrorProvider(getSyntaxErrorProvider());
		parser.setUnorderedGroupHelper(getUnorderedGroupHelper().get());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	protected org.ow2.mindEd.idt.editor.textual.parser.antlr.internal.InternalFractalIdtParser createParser(XtextTokenStream stream) {
		return new org.ow2.mindEd.idt.editor.textual.parser.antlr.internal.InternalFractalIdtParser(stream, getElementFactory(), getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "IdtFile";
	}
	
	public FractalIdtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FractalIdtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
