/*
 * generated by Xtext
 */
package org.ow2.fractal.mind.idl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FractalIdtRuntimeModule extends org.ow2.fractal.mind.idl.AbstractFractalIdtRuntimeModule {

}
