/*
 * generated by Xtext
 */
package org.ow2.fractal.mind.idl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author Rémi Mélisson
 * @contributor Damien Fournier
 */

public class FractalIdtUiModule extends org.ow2.fractal.mind.idl.ui.AbstractFractalIdtUiModule {
	public FractalIdtUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	/**
	 * Using ITF lexical highlighting
	 * 
	 */
	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return LexicalHighlightingConfiguration.class;
	}

	/**
	 * Using IDT token
	 * 
	 */
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper() {
		return AntlrIDTTokenToAttributeIdMapper.class;
	}
	
}
