/*
 * generated by Xtext
 */
package org.ow2.mindEd.itf.editor.textual.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FractalItfUiModule extends org.ow2.mindEd.itf.editor.textual.ui.AbstractFractalItfUiModule {
	public FractalItfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
